default: true

heading-increment: true # MD001

heading-style: # MD003
  style: atx

ul-indent: # MD007
  indent: 2

line-length: # MD013
  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100
  code_blocks: false
  tables: false
  headings: false
  strict: false
  stern: true

no-duplicate-heading: # MD024
  siblings_only: true

single-h1: false # MD025

no-inline-html: # MD033
  allowed_elements: ["img", "br", "details", "summary", "kbd", "security", "tauri", "task", "important", "remember", "instruction"]

first-line-h1: false # MD041
