# Speakr Rust formatting configuration
# Stable channel only - based on project requirements:
# 100 char max, trailing commas, organised imports

# Basic formatting (stable)
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
edition = "2021"

# Import organisation (stable)
reorder_imports = true
reorder_modules = true

# Width settings (stable)
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50

# Function parameters (stable - using updated parameter name)
fn_params_layout = "Tall"

# Miscellaneous (stable)
remove_nested_parens = true
use_field_init_shorthand = false
