name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    - name: Install mdbook and plugins
      run: |
        cargo install mdbook
        cargo install mdbook-admonish
        cargo install mdbook-mermaid
      shell: bash

    - name: Install plugin assets (admonish & mermaid)
      working-directory: docs
      run: |
        mdbook-admonish install .
        mdbook-mermaid install .
      shell: bash
