[book]
title = "Speakr Documentation"
authors = ["David Jessup"]
description = "Detailed product, architecture, and usage documentation for Speakr— the privacy-first dictation hot-key utility."
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/djessup/speakr"
additional-css = ["theme/custom.css"]

[output.html.search]
use-boolean-and = true
